### ISSUE TITLE
missingNetworkPolicy should not check ingress/egress rule count

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [FairwindsOps/polaris#1088]
### What happened?

the [missingNetworkPolicy](https://github.com/FairwindsOps/polaris/blob/master/pkg/config/checks/missingNetworkPolicy.yaml) check is currently enforcing at least one ingress/egress rule.

for plain webservers i don't want to allow any egress rule, also we have jobs which only have egress traffic.

### What did you expect to happen?

the check should only over the `policyTypes` as it's automatically denying traffic if no rules are defined.

### How can we reproduce this?

use netpol like:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webserver
spec:
  podSelector:
    matchLabels:
      app: webserver
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Ingress
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress
    ports:
    - protocol: TCP
      port: 8000
```

### Version

9.6.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
