### ISSUE TITLE
static content is not loaded when using nginx-ingress with custom base path

### ISSUE THREAD

**Issue by troian** [FairwindsOps/polaris#132]
We would like to get polaris dashboard accessible from subpath of our domain (e.g. `https://example.com/polaris`)

Issue is static content is not loaded as deployment expects them without `polaris` path.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example.com-polaris
  namespace: polaris
  annotations:
    kubernetes.io/ingress.provider: "nginx"
    kubernetes.io/ingress.class: "nginx-ks"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/polaris)$ $1/ permanent;
spec:
  tls:
    - hosts:
        - example.com
      secretName: star-example-com
  rules:
    - host: cluster.notifai.io
      http:
        paths:
          - path: /polaris/?(.*)
            backend:
              serviceName: polaris-dashboard
              servicePort: 8080
```

**Comment by bobby-brennan** [comment]
Thanks for the report! This was fixed in `0.1.5`.

To serve the dashboard on a base path like `/polaris`, you'll need to set `--dashboard-base-path="/polaris/"`

#136 will add this as an option to the helm chart. You can also alter the file at `./deploy/dashboard.yaml`.

Hope that helps! Let me know if you have any trouble.

**Comment by troian** [comment]
Does not seem to work unfortunately.
When trying to access dashboard [within internal link](http://polaris-dashboard.polaris.svc.cluster.local) without custom path it works fine

adding `--dashboard-base-path="/polaris/"` breaks that so neither `example.com/polaris/` nor [internal link](http://polaris-dashboard.polaris.svc.cluster.local) works

**Comment by rbren** [comment]
@troian - sorry, I missed your follow-up message. I've reopened this issue for now.

When I set up an Ingress similar to yours using nginx-ingress (config below), combined with the `--dashboard-base-path` flag, example.com/polaris works as expected (though accessing the service via `kubectl port-forward` doesn't work).

We have an [open PR](https://github.com/FairwindsOps/polaris/pull/201#issuecomment-535693440) that would mount the router on the path provided in `--dashboard-base-path`, which I think would obviate the need for the rewrite rule, and allow both the service and the external URL to work.

Here's my Ingress, which works as expected:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example.com-polaris
  namespace: polaris
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
    kubernetes.io/ingress.ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/polaris)$ $1/ permanent;
spec:
  tls:
    - hosts:
        - polaris.example.com
      secretName: polaris-cert
  rules:
    - host: polaris.example.com
      http:
        paths:
          - path: /polaris/?(.*)
            backend:
              serviceName: polaris-dashboard
              servicePort: 8080
```
