### ISSUE TITLE
Example configs don't contain displayName

### ISSUE THREAD

**Issue by endzyme** [FairwindsOps/polaris#158]
The example configs don't contain an example of setting the display name in yaml configs. 

Also `--display-name` is missing from the `README.md` docs for flags

**Comment by alexcurtin** [comment]
Cross posting here as I didn't read well on your original post on this issue.

I have tried adding `displayName` and `clusterName` in the config, as well as the values file, but no matter what the `polaris` binary complains about unknown flags (either -display-name or -cluster-name).

```
apiVersion: v1
data:
  config.yaml: |
    displayName: hello-world
    resources:
      cpuRequestsMissing: warning
      cpuLimitsMissing: warning
      memoryRequestsMissing: warning
      memoryLimitsMissing: warning
    images:
      tagNotSpecified: error
    healthChecks:
      readinessProbeMissing: warning
      livenessProbeMissing: warning
    networking:
      hostNetworkSet: warning
      hostPortSet: warning
    security:
      hostIPCSet: error
      hostPIDSet: error
      notReadOnlyRootFileSystem: warning
      privilegeEscalationAllowed: error
      runAsRootAllowed: warning
      runAsPrivileged: error
      capabilities:
        error:
          ifAnyAdded:
            - SYS_ADMIN
            - NET_ADMIN
            - ALL
        warning:
          ifAnyAddedBeyond:
            - CHOWN
            - DAC_OVERRIDE
            - FSETID
            - FOWNER
            - MKNOD
            - NET_RAW
            - SETGID
            - SETUID
            - SETFCAP
            - SETPCAP
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - KILL
            - AUDIT_WRITE
kind: ConfigMap
```

or 

```
displayName: helloworld
dashboard:
  displayName: hello-world
  enable: true
  clusterName: "example"
  replicas: 1
  service:
    type: NodePort
  image:
    repository: quay.io/reactiveops/polaris
    tag: 0.2.1
    pullPolicy: Always
```
none of these options appear to work :(
