### ISSUE TITLE
LimitRange is ignored for cpu/mem limit/range report.

### ISSUE THREAD

**Issue by ismailbaskin** [FairwindsOps/polaris#163]
We are using LimitRange for some namespaces. But Polaris still shows "CPU requests should be set" warning.
```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - defaultRequest:
      cpu: 50m
      memory: 256Mi
    default:
      cpu: 200m
      memory: 256Mi
    type: Container
```
