### ISSUE TITLE
RunAsNonRoot should pass if securityContext.runAsUser != 0

### ISSUE THREAD

**Issue by coreypobrien** [FairwindsOps/polaris#192]
In the check for `RunAsRootAllowed`, polaris isn't considering if the container spec specifically runs as a non-root user. The code only checks for `securityContext.RunAsNonRoot`:
https://github.com/FairwindsOps/polaris/blob/b8422a93b7a2ab3a81b288f283ff3525a39db726/pkg/validator/container.go#L209-L226

### Expected Behavior
This deployment should not fail the `RunAsRootAllowed` check:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: runasdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runasdemo
  template:
    metadata:
      labels:
        app: runasdemo
    spec:
      containers:
        - name: demo
          image: "k8s.gcr.io/defaultbackend-amd64:1.5"
          securityContext:
            runAsUser: 65534
```

### Actual Behavior
If fails the check even though it is clearly not running as root.

### Steps to Reproduce
1. Create the Deployment above
2. Run `polaris --audit | jq '.NamespacedResults.default.DeploymentResults[] | select(.Name=="runasdemo") | .PodResult.ContainerResults[].Messages[] | select(.Message=="Should not be allowed to run as root")'`
