### ISSUE TITLE
Webhook does not cover all possible versions of deployments

### ISSUE THREAD

**Issue by ingshtrom** [FairwindsOps/polaris#244]
### Installation Process
I manually installed the dashboard and webhook into an EKS cluster via the [instructions here](https://github.com/FairwindsOps/polaris/blob/master/docs/usage.md#dashboard).

Nothing was modified, except increasing the log level on the webhook deployment.

### Polaris Version
```
0.6
```

### Expected Behavior
My deployment gets restricted

### Actual Behavior
I can deploy my test application without issues.

### Steps to Reproduce
1. `kubectl apply -f file.yaml` YAML from below.

Alternatively, if the YAML is modified so that it reads `apisVersion: apps/v1`, then `kubectl apply -f ...` fails as expected. 

### Additional Context
Here is the YAML I'm deploying to my cluster via `kubectl apply -f file.yaml`
```
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: router-test
  namespace: infra-system
spec:
  selector:
    matchLabels:
      app: router-test
  replicas: 1
  template:
    metadata:
      labels:
        app: router-test
    spec:
      restartPolicy: Always
      containers:
        - name: web
          image: nginx
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80

```

I also inspected the ValidationWebhookConfiguration that is generated the the `polaris-webhook` container, and it seems that it does only bind against the `apps/v1` apis for `deployment` objects. I haven't written a webhook validator before, but my _hunch_ is that is where the problem lies. Honestly, I'm curious why Kubernetes doesn't deprecate the old versions of the API in the first place :man_shrugging:.

It would be cool if as an operator I could restrict the APIs that people using a cluster could use via the Polaris tool, but I realize that likely adds a lot of complexity in re-generating the `ValidationWebhookConfiguration` every time the configmap is modified... or maybe we just need _restart_ the webhook pod and we're good? :thinking: 

### References
n/a
