### ISSUE TITLE
Check fields that can appear in both Pod and Container objects

### ISSUE THREAD

**Issue by hgoscenski-vail** [FairwindsOps/polaris#336]
Some fields can appear in both the Pod level securityContext as well as the container level securityContext for example runAsUser.

I was wondering if there is a way to check both consistently or if the only solution at this time is to have 2 checks, one for pod level and one for container level.

**Comment by hgoscenski-vail** [comment]
This check below successfully validates that the container level runAsUser but does not verify the pod level runAsUser. The deployment below passes but it would be very nice if polaris could catch the incorrect pod level runAsUser without a seperate check.

```bash
[2:05:27] ~ λ polaris audit -c polarisyaml --audit-path deploy.yaml
{
  "PolarisOutputVersion": "1.0",
  "AuditTime": "0001-01-01T00:00:00Z",
  "SourceType": "Path",
  "SourceName": "deploy.yaml",
  "DisplayName": "deploy.yaml",
  "ClusterInfo": {
    "Version": "unknown",
    "Nodes": 0,
    "Pods": 1,
    "Namespaces": 0,
    "Controllers": 1
  },
  "Results": [
    {
      "Name": "centos-test",
      "Namespace": "",
      "Kind": "Deployment",
      "Results": {},
      "PodResult": {
        "Name": "",
        "Results": {},
        "ContainerResults": [
          {
            "Name": "centos",
            "Results": {
              "fsGroup2427": {
                "ID": "fsGroup2427",
                "Message": "fsGroup is 2427",
                "Success": true,
                "Severity": "warning",
                "Category": "Security"
              }
            }
          }
        ]
      },
      "CreatedTime": "0001-01-01T00:00:00Z"
    }
  ]
}%
```

```yaml
# polaris.yaml
checks:
  fsGroup2427: warning
customChecks:
  fsGroup2427:
    successMessage: fsGroup is 2427
    failureMessage: fsGroup is not 2427
    category: Security
    target: Container
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      properties:
        securityContext:
          type: object
          properties:
            runAsUser:
              type: integer
              allOf:
                - minimum: 2427
                - maximum: 2427
```

Sample deployment:

```yaml
# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    test-polatis-annotation: test-polaris-annotation
  labels:
    app: centos-test
  name: centos-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-test
  template:
    metadata:
      annotations:
        test-polatis-annotation: test-polaris-annotation
      labels:
        app: centos-test
    spec:
      containers:
      - image: centos:7
        name: centos
        securityContext:
          runAsUser: 2427
      securityContext:
        runAsUser: 247
status: {}
```
