### ISSUE TITLE
Possible to query object metadata?

### ISSUE THREAD

**Issue by k45c4d3** [FairwindsOps/polaris#338]
Having trouble querying object metadata, in this case pod labels.

Custom check: 
```
    podNameLabelExists:
    successMessage: label is correct
    failureMessage: label is incorrect or missing
    target: Pod
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      required:
      - metadata
      properties:
        metadata:
          type: object
          properties:
            labels:
              type: object
              properties:
                app:
                  pattern: ^label-test
```

Test deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: label-test
  name: polaris-test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-test
  strategy: {}
  template:
    metadata:
      labels:
        app: label-test
    spec:
      containers:
      - image: centos:7
        name: centos
        resources: {}
```

Using `required: metadata` in the check causes audits to fail every single time, so I'm wondering if this is possible at all or if I'm just not understanding how exactly to do this.

Also, when not enforcing required: metadata, every audit passes regardless of the actual labels being correct or not.

Without required: metadata (all of these pass always)
```
          "podNameLabelExists": {
            "ID": "podNameLabelExists",
            "Message": "label is correct",
            "Success": true,
            "Severity": "warning",
            "Category": ""
          }
```

With required: metadata: 
```
          "podNameLabelExists": {
            "ID": "podNameLabelExists",
            "Message": "label is incorrect or missing",
            "Success": false,
            "Severity": "warning",
            "Category": ""
          }
```

**Comment by k45c4d3** [comment]
Sorry for the delay getting back to you on this.

To clarify right now I'm primarily interested in the `spec.template.metadata.labels`

So far I haven't gotten it to work. I took your exact config from above and used it as the config file to run an audit on the sample deployment manifest in the original comment. This is how I have been testing all of my checks so far. I get success no matter what the label is.

`polaris audit -c ~/Desktop/polarisconf.yaml --audit-path ~/Desktop/polaristestchecks.yaml --log-level debug`

```spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-test
  strategy: {}
  template:
    metadata:
      labels:
        app: label-test
```
```
  "Results": [
    {
      "Name": "polaris-test-deploy",
      "Namespace": "",
      "Kind": "Deployment",
      "Results": {},
      "PodResult": {
        "Name": "",
        "Results": {
          "podNameLabelExists": {
            "ID": "podNameLabelExists",
            "Message": "label is correct",
            "Success": true,
            "Severity": "warning",
            "Category": ""
```
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-test
  strategy: {}
  template:
    metadata:
      labels:
        app: INCORRECT_LABEL
    spec:
      containers:
      - image: centos:7
        name: centos
        resources: {}
```
```
 "Results": [
    {
      "Name": "polaris-test-deploy",
      "Namespace": "",
      "Kind": "Deployment",
      "Results": {},
      "PodResult": {
        "Name": "",
        "Results": {
          "podNameLabelExists": {
            "ID": "podNameLabelExists",
            "Message": "label is correct",
            "Success": true,
            "Severity": "warning",
            "Category": ""
```

**Comment by mambax** [comment]
Same for me

```yaml
  customChecks:
    maintainerTeamMissing:
      successMessage: Maintainer Team is set
      failureMessage: Maintainer Team should be set (maintainer_team, sre)
      target: Pod
      schema:
        '$schema': http://json-schema.org/draft-07/schema
        type: object
        properties:
          template:
            required:
              - metadata
            properties:
              metadata:
                type: object
                required:
                  - labels
                properties:
                  labels:
                    type: object
                    required:
                    - maintainer_team
                    - sre
                    properties:
                      maintainer_team:
                        pattern: ^data-.*
                      sre:
                        pattern: ^data-.*
```

This check is always true, no team at us is named data 😕
