### ISSUE TITLE
Handle case where no checks are enabled

### ISSUE THREAD

**Issue by mambax** [FairwindsOps/polaris#339]
![image](https://user-images.githubusercontent.com/5472171/84284078-0c3e0500-ab3c-11ea-9adf-186185a1910c.png)
Hi all
Sorry to hop in with such a beginner question, but I struggle to get the most basic custom check to run (see image).

My config is (copied from [config-full.yml](https://github.com/FairwindsOps/polaris/blob/master/examples/config-full.yaml)):

```yaml
config:
  customChecks:
    resourceLimits:
      containers:
        exclude:
          - initContainer
      successMessage: Resource limits are within the required range
      failureMessage: Resource limits should be within the required range
      category: Resources
      target: Container
      schema:
        '$schema': http://json-schema.org/draft-07/schema
        type: object
        required:
          - resources
        properties:
          resources:
            type: object
            required:
              - limits
            properties:
              limits:
                type: object
                required:
                  - memory
                  - cpu
                properties:
                  memory:
                    type: string
                    resourceMinimum: 100M
                    resourceMaximum: 6G
                  cpu:
                    type: string
                    resourceMinimum: 100m
                    resourceMaximum: "2"

```
Yes, I just do one check to test.
If I remove the custom check and add the rest of the config it works as expected.

Why is my UI looking so strange? I am happy to provide more files but given I used the official example I doubt it helps.

One of the entries looks like:
![image](https://user-images.githubusercontent.com/5472171/84284483-8a021080-ab3c-11ea-830e-04187e2a474b.png)

Am I looking in the wrong direction?
Thanks for any hint
