### ISSUE TITLE
Query Object Metadata

### ISSUE THREAD

**Issue by k45c4d3** [FairwindsOps/polaris#351]
Linking closed issue https://github.com/FairwindsOps/polaris/issues/338

@rbren 

Sorry for the delay getting back to you on this.

To clarify right now I'm primarily interested in the `spec.template.metadata.labels`

So far I haven't gotten it to work. I took your exact config from above and used it as the config file to run an audit on the sample deployment manifest in the original comment. This is how I have been testing all of my checks so far. I get success no matter what the label is.

`polaris audit -c ~/Desktop/polarisconf.yaml --audit-path ~/Desktop/polaristestchecks.yaml --log-level debug`

```spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-test
  strategy: {}
  template:
    metadata:
      labels:
        app: label-test
```
```
  "Results": [
    {
      "Name": "polaris-test-deploy",
      "Namespace": "",
      "Kind": "Deployment",
      "Results": {},
      "PodResult": {
        "Name": "",
        "Results": {
          "podNameLabelExists": {
            "ID": "podNameLabelExists",
            "Message": "label is correct",
            "Success": true,
            "Severity": "warning",
            "Category": ""
```
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-test
  strategy: {}
  template:
    metadata:
      labels:
        app: INCORRECT_LABEL
    spec:
      containers:
      - image: centos:7
        name: centos
        resources: {}
```
```
 "Results": [
    {
      "Name": "polaris-test-deploy",
      "Namespace": "",
      "Kind": "Deployment",
      "Results": {},
      "PodResult": {
        "Name": "",
        "Results": {
          "podNameLabelExists": {
            "ID": "podNameLabelExists",
            "Message": "label is correct",
            "Success": true,
            "Severity": "warning",
            "Category": ""
```

**Comment by samuelb** [comment]
Looks like the checks with `target: Pod` only looks at `spec.template.spec` and below.

eg. when looking at this Deployment spec:
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        app: INCORRECT_LABEL
    spec:
      containers:
      - image: centos:7
        name: centos
        resources: {}
```
This customChecks rule would be successfully:
```
testCustomChecks:
  successMessage: All OK
  failureMessage: Nothing is OK
  target: Pod
  schema:
  '$schema': http://json-schema.org/draft-07/schema
  required:
  - containers
```
as underneath `spec.template.spec` a key `containers` exists. This also means that `spec.template.metadata` is outside the scope.

The examples https://github.com/FairwindsOps/polaris/issues/338#issuecomment-642047617 or https://github.com/FairwindsOps/polaris/issues/338#issuecomment-642747135 are always be successful as there is `schema.required: [template]` missing.

Following worked in my quick tests (please note `target: Controller`) :
```
customChecks:
  podNameLabelExists:
    successMessage: label is correct
    failureMessage: label is incorrect or missing
    target: Controller
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - template
          properties:
            template:
              type: object
              required:
                - metadata
              properties:
                metadata:
                  type: object
                  required:
                    - labels
                  properties:
                    labels:
                      type: object
                      required:
                        - app
                      properties:
                        app:
                          pattern: ^label-test
```

However, the result is not visible on the polaris dashboard but when run `polaris audit ...`.

**Comment by rbren** [comment]
Sorry for the delay - was out on PTO

I think this is a small syntax issue - we've run into it before. We should work to simplify this.

In addition to specifying `customChecks`, you need to specify the severity level in the `checks` section. So your config should be

```yaml
checks:
  podNameLabelExists: danger

customChecks:
  podNameLabelExists:
    successMessage: label is correct
    failureMessage: label is incorrect or missing
    target: Controller
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - template
          properties:
            template:
              type: object
              required:
                - metadata
              properties:
                metadata:
                  type: object
                  required:
                    - labels
                  properties:
                    labels:
                      type: object
                      required:
                        - app
                      properties:
                        app:
                          pattern: ^label-test
```

With that, the check fails correctly for me.

I realize that's confusing - you're not the first person to get tripped up by it. Opened https://github.com/FairwindsOps/polaris/issues/359 to track

**Comment by mambax** [comment]
Hi @rbren 
Nice to have you back
@samuelb works with me together on our journey to get Polaris "production" ready.

He did not post the complete config, we actually have the check enabled.

config.yaml (we changed the ConfigMap to read from a file, so we can use it in CLI as file too):
```
checks:
  # resources
  cpuRequestsMissing: warning
  cpuLimitsMissing: warning
  memoryRequestsMissing: warning
  memoryLimitsMissing: warning

  # resources:custom
  resourceLimits: warning

  # maintenance
  maintainerTeamMissing: warning

#
# custom checks
#
customChecks:
  maintainerTeamMissing:
    successMessage: Maintainer Team is set
    failureMessage: Maintainer Team should be set (maintainer_team, sre)
    target: Controller
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - template
          properties:
            template:
              type: object
              required:
                - metadata
              properties:
                metadata:
                  type: object
                  required:
                    - labels
                  properties:
                    labels:
                      type: object
                      required:
                        - maintainer_team
                        - sre
                      properties:
                        maintainer_team:
                          type: string
                          not:
                            const: null
                        sre:
                          type: string
                          not:
                            const: null

  resourceLimits:
    containers:
      exclude:
        - initContainer
    successMessage: Resource limits are within the required range
    failureMessage: Resource limits should be within the required range
    category: Resources
    target: Container
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      required:
        - resources
      properties:
        resources:
          type: object
          required:
            - limits
          properties:
            limits:
              type: object
              required:
                - memory
                - cpu
              properties:
                memory:
                  type: string
                  resourceMinimum: 100Mi
                  resourceMaximum: 8Gi
                cpu:
                  type: string
                  resourceMinimum: 100m
                  resourceMaximum: "3"

```

But, as @samuelb wrote this leads to the following issue:
**While DASHBOARD shows nothing about the team at all, audit lists it as success:false perfectly!**

![image](https://user-images.githubusercontent.com/5472171/85329530-f7198c80-b4d2-11ea-9122-4f7a9c11bde7.png)

![image](https://user-images.githubusercontent.com/5472171/85329585-16181e80-b4d3-11ea-9bdd-28d01266fe1b.png)

This miiiight be another issue tho as the original check runs, just not in dashboard :)
