### ISSUE TITLE
Add Validation for Image Pattern Matching

### ISSUE THREAD

**Issue by robscott** [FairwindsOps/polaris#37]
We should have a list of patterns that an image attribute must match one of, or a list of patterns that an image attribute should not match any of. Generally these would never be set at the same time, but I can't think of any reason we need to add any logic to ensure that they're never both set. I think the most sensible approach here is to ensure that `container.image` matches at least one pattern defined in the whitelist or does not match any patterns defined in the blacklist. We do not want to do full regex matching here, but supporting a `*` wildcard character would simplify things. Ideally we could create a small method that determined if a blacklist or whitelist item matched a string, and then write a bunch of unit tests to cover use cases like:

`quay.io/reactiveops*` 
- `quay.io/reactiveops` (invalid)
- `quay.io/reactiveops/` (valid)
- `quay.io/unreactiveops` (invalid)
- `quay.io/reactiveops/rbac-manager` (valid)

`quay.io/*ops*` 
- `quay.io/reactiveops` (invalid)
- `quay.io/reactiveops/` (valid)
- `quay.io/unreactiveops` (valid)
- `quay.io/reactiveops/rbac-manager` (valid)

`quay.io/reactiveops/rbac-manager` 
- `quay.io/reactiveops` (invalid)
- `quay.io/reactiveops/` (invalid)
- `quay.io/unreactiveops` (invalid)
- `quay.io/reactiveops/rbac-manager` (valid)

**Comment by towolf** [comment]
> We do not want to do full regex matching here

Just a note, if you will. We had this discussion ourselves 2 years ago and we agreed that anybody who is interested in policing images is likely to be well versed in regex. So we just went with it:

https://github.com/freach/docker-image-policy-plugin/#plugin-configuration

Sometimes the regex is really necessary:

```
image-policy:                                            
  defaultAllow: false                                    
                                                         
  blacklist: []                                          
    # - ':latest$'                                       
    # - ':master$'                                       
                                                         
  whitelist:                                             
    # allow anything from gitlab registry                
    - '^gitlab\.example\.com:5005'                         
                                                         
    # not sure we need these at all                      
    # only for one-off usage                             
    - '^alpine(:|$)'                                     
    - '^busybox(:|$)'                                    
    - '^maven(:|$)'     # used by platform for building  
    - '^memcached(:|$)' # used by socorro                
    - '^mysql(:|$)'     # used by gitlab ci/cd "service" 
    - '^nginx(:|$)'                                      
    - '^node(:|$)'                                       
    - '^python(:|$)'                                     
    - '^ubuntu(:|$)'                                     
                                                         
    # k8s cluster components                             
    - '^k8s\.gcr\.io'                       
                                                         
    # for e2e tests                                      
    - '^gcr\.io/google-samples'                          
    - '^gcr\.io/kubernetes-e2e-test-images'              
    - '^gcr\.io/google[_-]containers'                    
    - '^docker\.io/library/nginx:1\.1.-alpine'           
    - '^docker\.io/library/busybox:1\...'                
    - '^quay.io/coreos/etcd:v3\.'                        
```
