### ISSUE TITLE
Polaris Dashboard and polaris cli output discrepancies

### ISSUE THREAD

**Issue by blame19** [FairwindsOps/polaris#382]
### Installation Process
Polaris dashboard was installed with helm on a kubernetes cluster. 
Chart version : "1.1.0"
### Polaris Version
```
Polaris version:1.1.1
```

### Expected Behavior
After setting up the current exemptions in the polaris configmap, through helm and a value file:

```
    - controllerNames:
      - prometheus-prometheus-operator-prometheus
      rules:
      - readinessProbeMissing
      - livenessProbeMissing
    - controllerNames:
      - prometheus-prometheus-operator-prometheus
      rules:
      - notReadOnlyRootFilesystem

```
I can correctly see my polaris dashboard listing the component as green:
![image](https://user-images.githubusercontent.com/11650257/88799279-81c26b00-d1a6-11ea-8dbd-37df4cda0ebc.png)

I expect that running polaris audit -c config (where config contains a list of the mentioned exemptions) I would get the same green status on all components.
### Actual Behavior

However, when running polaris audit -c config (where config contains a list of the mentioned exemptions) I get:
 ```
   {
      "Name": "prometheus-operator-prometheus",
      "Namespace": "monitoring",
      "Kind": "Prometheus",
      "Results": {},
...
        "ContainerResults": [
          {
            "Name": "prometheus",
            "Results": {
...
              "notReadOnlyRootFilesystem": {
                "ID": "notReadOnlyRootFilesystem",
                "Message": "Filesystem should be read only",
                "Success": false,
                "Severity": "warning",
                "Category": "Security"
              },
....
          {
            "Name": "prometheus-config-reloader",
            "Results": {
...
              "livenessProbeMissing": {
                "ID": "livenessProbeMissing",
                "Message": "Liveness probe should be configured",
                "Success": false,
                "Severity": "warning",
                "Category": "Health Checks"
              },
```

Namely polaris dashboard lists the component correctly with the name it has on my cluster: prometheus-prometheus-operator-prometheus

The audit, for some reason, lists it as prometheus-operator-prometheus. I think it might be due to the lenght of the controller name or a difference between the chart and the cli versions. Could you confirm?
