### ISSUE TITLE
images.pullPolicyNotAlways Default Appears to be Warning (not Ignore as in Documentation)

### ISSUE THREAD

**Issue by larkintuckerllc** [FairwindsOps/polaris#403]
### Installation Process
 

Followed Dashboard Quickstart yesterday (8/30/2020).

```
kubectl apply -f https://github.com/FairwindsOps/polaris/releases/latest/download/dashboard.yaml
kubectl port-forward --namespace polaris svc/polaris-dashboard 8080:80
```

### Polaris Version

Running inside of Kubernetes.

```
    Image:         quay.io/fairwinds/polaris:1.2
    Image ID:      quay.io/fairwinds/polaris@sha256:a15082f000cb2ed036362bc9c83434399a4f3fe22b4ba4ca72ee2f71dba79bc9
```

### Expected Behavior

Running a Pod as follows:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-polaris
  name: hello-polaris
spec:
  containers:
  - image: sckmkny/hello-polaris:0.1.0
    name: hello-polaris
    ports:
    - containerPort: 8080
```

While it is true in this  case the imagePullPolicy is not set to Always.

```
    imagePullPolicy: IfNotPresent
```

The documentation (clicking on help in Dashboard to URL: http://localhost:8080/details/images) shows as follows:

```
images.pullPolicyNotAlways | ignore | Fails when an image pull policy is not always.
```

Assumed that because it defaulted to "ignore" I would not see a warning in the Dashboard.

### Actual Behavior

The check "Image pull policy should be "Always"" shows as a warning.

### Steps to Reproduce

See above.

### Additional Context

N/A

### References

N/A
