### ISSUE TITLE
static content is not loaded when using nginx-ingress with custom base path

### ISSUE THREAD

**Issue by osaffer** [FairwindsOps/polaris#431]
Hi,

I installed polaris 1.2 by applying the yaml file, I can access the page, but, some contents are not loaded.

In a post, I saw about this parameter : --dashboard-base-path="/polaris/" but I did not see how to use it .

This is my ingress configuration:

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/polaris)$ $1/ permanent;
  name: polaris
  namespace: polaris
spec:
  rules:
  - host: hostname
    http:
      paths:
      - path: /polaris/?(.*)
        backend:
          serviceName: polaris-dashboard
          servicePort: 80

Thanks for your help

**Comment by baderbuddy** [comment]
Hi,

Incase anyone else finds this that installed with Helm, there's a parameter in the helm chart called `dashboard.basePath` that takes in the path and will configure everything for you.

In your case because you installed Polaris with the yaml file you'll need to modify your deployment and add `--base-path` and `/polaris/` to the command array.

The name changed from `dashboard-base-path` to `base-path` in Polaris 1.0

**Comment by osaffer** [comment]
Hi,

Thanks for your reply, very helpful of course,  but I tried different things but the pod cannot be ready

May you show the command sequence inside the yaml file ?

Thank you

**Comment by osaffer** [comment]
For example, this way:
spec:
      containers:
      - command:
        - polaris
        - dashboard
        - --base-path
        - /polaris/

pod/polaris-dashboard-789df88cc5-rf8pt   0/1     Running

kubectl logs -f -n polaris pod/polaris-dashboard-789df88cc5-rf8pt
time="2020-10-22T08:11:50Z" level=info msg="Starting Polaris dashboard server on port 8080"


I tried different ways, as for example 

- command: ["polaris", "dashboard", "--base-path", "/polaris"]

or

- command: ["polaris"]
   args: ["dashboard", "--base-path", "/polaris"]

etc ...

But without any success.

May you show me ?

Thank you.

**Comment by osaffer** [comment]
Ok, I did finally instally via helm, I deployed 
helm install polaris fairwinds-stable/polaris --namespace polaris --set dashboard.basePath=/polaris/

Then I checked the deployment, and it was set exactly as I had done ;-)

So it means there is was a bug.

So all fine now

**Comment by just1689** [comment]
For anyone not using Helm:

Modify the Deployment to match
```yaml
    spec:
      containers:
      - command:
        - polaris
        - dashboard
        - --base-path
        - /polaris/
```

and also the probes
```yaml
        livenessProbe:
          httpGet:
            path: /polaris/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /polaris/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 20
```

**Comment by just1689** [comment]
Consider adding to the docs in some way?

**Comment by osaffer** [comment]
So the probe is mandatory .

Thanks for adding this information .

**Comment by akokskis** [comment]
And for anyone using an ingress to expose the dashboard, at least with ingress-nginx, no rewrites are necessary.

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: polaris
spec:
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /polaris/
            backend:
              serviceName: polaris
              servicePort: 8080
```
