### ISSUE TITLE
Polaris cli should not fail if no checks are defined for the given manifests (eg. when auditing CRDs)

### ISSUE THREAD

**Issue by chgl** [FairwindsOps/polaris#439]
### Installation Process
 

Installed via GitHub Release.

### Polaris Version

```
Polaris version:1.2.1
```

### Expected Behavior

If YAML manifests are passed to polaris, for which no checks exist, it should successfully exit.

### Actual Behavior

I have a repository that only contains ArgoCD application manifests in one folder. When scanning the entire repo, this causes the polaris scan to fail:

```
AuditTime: "0001-01-01T00:00:00Z"
ClusterInfo:
  Controllers: 0
  Namespaces: 0
  Nodes: 0
  Pods: 0
  Version: unknown
DisplayName: '-'
PolarisOutputVersion: "1.0"
Results: []
SourceName: '-'
SourceType: Path
INFO[0000] Audit score of 0 is less than the provided minimum of 100
```

### Steps to Reproduce

1. create a CRD manifest `argo.yaml`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
```
2. Run 
```
polaris audit --audit-path - --set-exit-code-below-score 100 < argo.yaml
```
3. Get a failing audit `INFO[0000] Audit score of 0 is less than the provided minimum of 100 `
