### ISSUE TITLE
support skip on container (im not sure if i have missed something)

### ISSUE THREAD

**Issue by dbones** [FairwindsOps/polaris#485]
### Installation Process

Helm chart on a K3s/k8s Cluster

```sh
helm upgrade --install polaris fairwinds-stable/polaris --namespace polaris -f polaris.yaml
```

### Polaris Version

using the latest version, which says 3.0 on the docker container

### Expected Behavior

skip (apply exemption to) any  container named `istio-init` and `istio-proxy`, in any deployment, in any namespace, that has these containers 

```yaml
  - containerNames:
      - istio-init
      - istio-proxy
    rules:
      - runAsRootAllowed
      - notReadOnlyRootFilesystem
      - dangerousCapabilities
      - insecureCapabilities
      - livenessProbeMissing
```

### Actual Behavior

The exemption is not being applied. 

### Steps to Reproduce

1. setup a cluster
2. setup Istio on the cluster
3. deploy 2 services that have Istio injection enabled (so the 2 pods will be auto injected on each service deployment) and that each server is in a different namespace
4. create a config file, example below (polaris.yaml)
5.
```sh
kubectl create namespace polaris
helm upgrade --install polaris fairwinds-stable/polaris --namespace polaris -f polaris.yaml
kubectl port-forward --namespace polaris svc/polaris-dashboard 8080:80
```

### Additional Context

We have noted that issue #408 was meant to fix this issue, however, is there something we have done incorrectly?

### References

- #408 
- https://github.com/FairwindsOps/polaris/issues/408#issuecomment-767386540 (shows the screenshot of the output)

EXAMPLE polaris.yaml file:

```yaml
config:
  checks:
    # reliability
    multipleReplicasForDeployment: ignore
    priorityClassNotSet: ignore
    tagNotSpecified: danger
    pullPolicyNotAlways: ignore
    readinessProbeMissing: warning
    livenessProbeMissing: warning
    # efficiency
    cpuRequestsMissing: danger
    cpuLimitsMissing: danger
    memoryRequestsMissing: danger
    memoryLimitsMissing: danger
    # security
    hostIPCSet: danger
    hostPIDSet: danger
    notReadOnlyRootFilesystem: danger
    privilegeEscalationAllowed: danger
    runAsRootAllowed: danger
    runAsPrivileged: danger
    dangerousCapabilities: danger
    insecureCapabilities: danger
    hostNetworkSet: danger
    hostPortSet: danger

  exemptions:

  - namespace: kube-system
    controllerNames:
      - dns-controller
    rules:
      - hostNetworkSet

  - namespace: kube-system
    controllerNames:
      - coredns
    rules:
      - cpuLimitsMissing
      - runAsRootAllowed
      - insecureCapabilities

  - controllerNames:
      - metrics-server
    rules:
      - runAsRootAllowed
      - notReadOnlyRootFilesystem
      - cpuLimitsMissing
      - cpuRequestsMissing
      - memoryLimitsMissing
      - memoryRequestsMissing
      - livenessProbeMissing
      - readinessProbeMissing

  - namespace: istio-system
    controllerNames:
      - istio-citadel
      - istio-galley
      - istio-ingressgateway
      - istio-pilot
      - istio-policy
      - istio-sidecar-injector
      - istio-telemetry
      - istio-tracing
      - kiali
    rules:
      - notReadOnlyRootFilesystem
      - runAsRootAllowed

      - memoryLimitsMissing
      - memoryRequestsMissing
      - cpuLimitsMissing
      - cpuRequestsMissing
      - livenessProbeMissing
      - readinessProbeMissing

  - containerNames:
      - istio-init
      - istio-proxy
    rules:
      - runAsRootAllowed
      - notReadOnlyRootFilesystem
      - dangerousCapabilities
      - insecureCapabilities
      - livenessProbeMissing
```
