### ISSUE TITLE
How add exemptions for a  namespace

### ISSUE THREAD

**Issue by skyox** [FairwindsOps/polaris#488]
How add exemptionfor whole namespace?

```
    exemptions:
      - namespace: kube-system
      - namespace: kube-public 
      - namespace: default
      - namespace: istio-system
      - namespace: kube-node-lease
      -
```
