### ISSUE TITLE
Custom Check to validate Volumes Mounts

### ISSUE THREAD

**Issue by dbones** [FairwindsOps/polaris#491]
I require to restrict `hostPath` volumes, which would look like this in a PSP

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  # other this to validate.
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
```
that prevents the following in our deployment:

```yaml
  volumes:
  - hostPath:
      path: /
      type: ""
    name: host-os
```
but I'm not sure how to apply something similar to the above PSP.

I have looked at the custom checks, however, I do not know what target schema is. Is there a definition of what target types are and what they look like 

for example, I am looking at this: https://github.com/FairwindsOps/polaris/blob/master/checks/runAsRootAllowed.yaml#L4
the target is the container, can I change that to volume?

any help here is appreciated (my main goal is to solve the volumes issue, but any extra info on the target schema's is a bonus)

**Comment by rbren** [comment]
The `target` field just helps so that you can target a container or pod spec in a generic way (since e.g. Deployments and CronJobs have them in different places inside their specs)

You can access the top-level object by specifying `target: Controller`, like in this check:
https://github.com/FairwindsOps/polaris/blob/master/checks/multipleReplicasForDeployment.yaml

**Comment by dbones** [comment]
@rbren thanks for the heads up

I have just written a custom check (below) and I think it's correct, whoever it's not showing as a failure on the report

note the metric server fails the rule but it has a blue bar, am i missing something?

![image](https://user-images.githubusercontent.com/183849/106795547-1de79600-6652-11eb-8d9d-ba455c19689a.png)

the custom rule:

```yaml
  DeploymentVolumeMounts:
    successMessage: Deployment using approved Volumes
    failureMessage: Deployment using unapproved and possibly dangerous Volumes
    category: Security
    target: Controller
    controllers:
      include:
      - Deployment
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - template
          properties:
            template:
              type: object
              required:
              - spec
              properties:
                spec:
                  type: object
                  required:
                  - volumes
                  properties:
                    volumes:
                      type: array
                      items:
                        anyOf:
                          - required:
                            - configMap
                          - required:
                            - secret
```
