### ISSUE TITLE
Support/document config options

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/polaris#499]
Polaris supports passing urls to the `--config` option. We should (a) document that and (b) support it in the helm chart

**Comment by rbren** [comment]
While we're at it, it'd be good to be able to pull in the config from a separate YAML file. @mambax shared this code:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polaris.fullname" $ }}
  {{- if $.Values.templateOnly }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels:
  {{- include "polaris.labels" $ | nindent 4 }}
data:
  config.yaml: |-
{{ .Files.Get "config.yaml" | indent 4 }}
{{- if .Values.exemptions }}
    exemptions:
{{ toYaml .Values.exemptions | indent 4 }}
{{- end }}
```
