### ISSUE TITLE
Polaris does not take PSP into account

### ISSUE THREAD

**Issue by zhelyan** [FairwindsOps/polaris#581]
### Installation Process
 

```
kubectl apply -f https://github.com/fairwindsops/polaris/releases/latest/download/dashboard.yaml
kubectl port-forward --namespace polaris svc/polaris-dashboard 8080:80
```
### Polaris Version

```
4.0.4
```

### Expected Behavior

No "Privilege escalation should not be allowed" alerts

### Actual Behavior

Container was flagged with: "Privilege escalation should not be allowed"

<img width="627" alt="Screenshot 2021-06-30 at 09 59 38" src="https://user-images.githubusercontent.com/1583967/123933038-e7f0d880-d989-11eb-966d-f10e45cc3e4c.png">

### Steps to Reproduce

```
cat <<EOF |  kubectl apply -f -
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: eks.restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: test-kube-schedule-scaler
  labels:
    app: test-kube-schedule-scaler
    product: test
    component: sleep
spec:
  selector:
    matchLabels:
      component: sleep
  replicas: 1
  template:
    metadata:
      labels:
        app: test-kube-schedule-scaler
        product: test
        component: sleep
    spec:
      terminationGracePeriodSeconds: 1
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
        runAsGroup: 65534
      containers:
        - name: sleep
          image: docker.io/library/busybox:1.33.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
          command: ['sleep', 'infinity']
EOF
```
