### ISSUE TITLE
Webhook and Dashboard misbehave on CronJob rule

### ISSUE THREAD

**Issue by andreamaruccia** [FairwindsOps/polaris#585]
### Installation Process
brew install kind
kind create cluster
helmfile -f polaris.yaml apply (see below)

### Polaris Version
version `4` installed with helmchart `4.0.4`

### Expected Behavior
Webhook should block the request
Dashboard should show the cronjob

### Actual Behavior
Webhook allows the request
Dashboard doesn't show the resource

### Steps to Reproduce
* create a certificates manifest called `cert.yaml`  with this content:
```
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: polaris-certificates
  namespace: polaris
data:
  ca.crt: add-your-keys
  tls.crt: add-your-keys
  tls.key: add-your-keys
```
* `kubectl create ns polaris`
* `kubectl apply -f cert.yaml -n polaris`

* `export POLARIS_CA_BUNDLE=your-bundle-ca`
* create a helmfile called polaris.yml
```
repositories:
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable

releases:
  - name: polaris
    namespace: polaris
    chart: fairwinds-stable/polaris
    version: 4.0.4
    values:
      - config: #The (polaris configuration)[https://github.com/FairwindsOps/polaris#configuration]. If not provided then the (default)[https://github.com/FairwindsOps/polaris/blob/master/examples/config.yaml] config from Polaris is used.
          customChecks:
            leaseplanTagsOnJopTemplateSpec:
              successMessage: Leaseplan tags have been correctly set on job template spec
              failureMessage: |
                Leaseplan tags are misconfigured on job template spec
                Mandatory tags:
                leaseplan/alert-channel
                leaseplan/entity
                leaseplan/environment
                leaseplan/owner
                leaseplan/owner
                leaseplan/product
                leaseplan/service
                leaseplan/version
              category: Reliability
              target: Controller
              controllers:
                include:
                - CronJob
              schema:
                '$schema': http://json-schema.org/draft-07/schema
                type: object
                properties:
                  spec:
                    type: object
                    required:
                      - jobTemplate
                    properties:
                      jobTemplate:
                        type: object
                        required:
                          - spec
                        properties:
                          spec:
                            type: object
                            required:
                              - template
                            properties:
                              template:
                                type: object
                                required:
                                  - metadata
                              properties:
                                metadata:
                                  type: object
                                  required:
                                    - annotations
                                  properties:
                                    annotations:
                                      type: object
                                      minProperties: 1
                                      # required:
                                      #   - leaseplan/alert-channel
                                      #   - leaseplan/entity
                                      #   - leaseplan/environment
                                      #   - leaseplan/owner
                                      #   - leaseplan/product
                                      #   - leaseplan/service
                                      #   - leaseplan/version
          checks:
            # reliability
            multipleReplicasForDeployment: ignore
            priorityClassNotSet: ignore
            tagNotSpecified: warning
            pullPolicyNotAlways: warning
            readinessProbeMissing: warning
            livenessProbeMissing: warning
            metadataAndNameMismatched: ignore
            pdbDisruptionsIsZero: warning
            missingPodDisruptionBudget: ignore
            leaseplanTagsOnJopTemplateSpec: danger

            # efficiency
            cpuRequestsMissing: danger
            cpuLimitsMissing: danger
            memoryRequestsMissing: danger
            memoryLimitsMissing: danger
            # security
            hostIPCSet: warning
            hostPIDSet: warning
            notReadOnlyRootFilesystem: warning
            privilegeEscalationAllowed: warning
            runAsRootAllowed: warning
            runAsPrivileged: warning
            dangerousCapabilities: warning
            insecureCapabilities: warning
            hostNetworkSet: warning
            hostPortSet: warning
            tlsSettingsMissing: warning

          exemptions:
            # velero CRD jobs install
            - namespace: velero
              controllerNames:
                - velero-upgrade-crds
              rules:
                - cpuRequestsMissing
                - cpuLimitsMissing
                - memoryRequestsMissing
                - memoryLimitsMissing
            # vpc tools installed by eksctl
            - namespace: kube-system
              controllerNames:
                - vpc-admission-webhook
                - vpc-resource-controller
              rules:
                - cpuRequestsMissing
                - cpuLimitsMissing
                - memoryRequestsMissing
                - memoryLimitsMissing
            # leaseplan tags in kube-system
            - namespace: kube-system
              rules:
                - leaseplanTagsOnJopTemplateSpec
            # leaseplan tags in polaris
            - namespace: polaris
              rules:
                - leaseplanTagsOnJopTemplateSpec
            # leaseplan tags in velero
            - namespace: velero
              rules:
                - leaseplanTagsOnJopTemplateSpec
            # leaseplan tags in kube-resource-report
            - namespace: kube-resource-report
              rules:
                - leaseplanTagsOnJopTemplateSpec
            # leaseplan tags in moon chart not supported
            - namespace: aerokube-moon
              rules:
                - leaseplanTagsOnJopTemplateSpec
            # istio install gets patched after install by choice
            - namespace: istio-system
              rules:
                - leaseplanNodeSelector
            # defaults by polaris
            - namespace: kube-system
              controllerNames:
                - kube-apiserver
                - kube-proxy
                - kube-scheduler
                - etcd-manager-events
                - kube-controller-manager
                - kube-dns
                - etcd-manager-main
              rules:
                - hostPortSet
                - hostNetworkSet
                - readinessProbeMissing
                - livenessProbeMissing
                - cpuRequestsMissing
                - cpuLimitsMissing
                - memoryRequestsMissing
                - memoryLimitsMissing
                - runAsRootAllowed
                - runAsPrivileged
                - notReadOnlyRootFilesystem
                - hostPIDSet

            - controllerNames:
                - kube-flannel-ds
              rules:
                - notReadOnlyRootFilesystem
                - runAsRootAllowed
                - notReadOnlyRootFilesystem
                - readinessProbeMissing
                - livenessProbeMissing
                - cpuLimitsMissing

            - controllerNames:
                - cert-manager
              rules:
                - notReadOnlyRootFilesystem
                - runAsRootAllowed
                - readinessProbeMissing
                - livenessProbeMissing

            - controllerNames:
                - cluster-autoscaler
              rules:
                - notReadOnlyRootFilesystem
                - runAsRootAllowed
                - readinessProbeMissing

            - controllerNames:
                - vpa
              rules:
                - runAsRootAllowed
                - readinessProbeMissing
                - livenessProbeMissing
                - notReadOnlyRootFilesystem

            - controllerNames:
                - datadog
              rules:
                - runAsRootAllowed
                - readinessProbeMissing
                - livenessProbeMissing
                - notReadOnlyRootFilesystem

            - controllerNames:
                - nginx-ingress-controller
              rules:
                - privilegeEscalationAllowed
                - insecureCapabilities
                - runAsRootAllowed

            - controllerNames:
                - dns-controller
                - datadog-datadog
                - kube-flannel-ds
                - kube2iam
                - aws-iam-authenticator
                - datadog
                - kube2iam
              rules:
                - hostNetworkSet

            - controllerNames:
                - aws-iam-authenticator
                - aws-cluster-autoscaler
                - kube-state-metrics
                - dns-controller
                - external-dns
                - dnsmasq
                - autoscaler
                - kubernetes-dashboard
                - install-cni
                - kube2iam
              rules:
                - readinessProbeMissing
                - livenessProbeMissing

            - controllerNames:
                - aws-iam-authenticator
                - nginx-ingress-default-backend
                - aws-cluster-autoscaler
                - kube-state-metrics
                - dns-controller
                - external-dns
                - kubedns
                - dnsmasq
                - autoscaler
                - tiller
                - kube2iam
              rules:
                - runAsRootAllowed

            - controllerNames:
                - aws-iam-authenticator
                - nginx-ingress-controller
                - nginx-ingress-default-backend
                - aws-cluster-autoscaler
                - kube-state-metrics
                - dns-controller
                - external-dns
                - kubedns
                - dnsmasq
                - autoscaler
                - tiller
                - kube2iam
              rules:
                - notReadOnlyRootFilesystem

            - controllerNames:
                - cert-manager
                - dns-controller
                - kubedns
                - dnsmasq
                - autoscaler
                - insights-agent-goldilocks-vpa-install
                - datadog
              rules:
                - cpuRequestsMissing
                - cpuLimitsMissing
                - memoryRequestsMissing
                - memoryLimitsMissing

            - controllerNames:
                - kube2iam
                - kube-flannel-ds
              rules:
                - runAsPrivileged

            - controllerNames:
                - kube-hunter
              rules:
                - hostPIDSet

            - controllerNames:
                - polaris
                - kube-hunter
                - goldilocks
                - insights-agent-goldilocks-vpa-install
              rules:
                - notReadOnlyRootFilesystem

            - controllerNames:
                - insights-agent-goldilocks-controller
              rules:
                - livenessProbeMissing
                - readinessProbeMissing

            - controllerNames:
                - insights-agent-goldilocks-vpa-install
                - kube-hunter
              rules:
                - runAsRootAllowed
        # END CONFIG
        image:
          # image.repository -- Image repo
          repository: quay.io/fairwinds/polaris
          # image.tag -- The Polaris Image tag to use. Defaults to the Chart's AppVersion
          tag: ""
          # image.pullPolicy -- Image pull policy
          pullPolicy: Always
          # image.pullSecrets -- Image pull secrets
          pullSecrets: []

        rbac:
          # rbac.enabled -- Whether RBAC resources (ClusterRole, ClusterRolebinding) should be created
          enabled: true

        serviceAccount:
          # serviceAccount.create -- Specifies whether a service account should be created
          create: true
          # serviceAccount.name -- The name of the service account to use.
          name:

        # templateOnly -- Outputs Namespace names, used with `helm template`
        templateOnly: false

        dashboard:
          # dashboard.basePath -- Path on which the dashboard is served. Defaults to `/`
          basePath: null
          # dashboard.enable -- Whether to run the dashboard.
          enable: true
          # dashboard.port -- Port that the dashboard will run from.
          port: 8080
          # dashboard.listeningAddress -- Dashboard listerning address.
          listeningAddress:
          # dashboard.replicas -- Number of replicas to run.
          replicas: 1
          # dashboard.podAdditionalLabels -- Custom additional labels on dashboard pods.
          podAdditionalLabels: {}
          # dashboard.resources -- Requests and limits for the dashboard
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 512Mi
          service:
            # dashboard.service.type -- Service Type
            type: ClusterIP
            # dashboard.service.annotations -- Service annotations
            annotations: {}
          # dashboard.nodeSelector -- Dashboard pod nodeSelector
          nodeSelector:
            kubernetes.io/os: linux
          # dashboard.tolerations -- Dashboard pod tolerations
          tolerations: []
          # dashboard.affinity -- Dashboard pods affinity
          affinity: {}
          ingress:
            # dashboard.ingress.enabled -- Whether to enable ingress to the dashboard
            enabled: false
            # dashboard.ingress.hosts -- Web ingress hostnames
            hosts:
            # dashboard.ingress.annotations -- Web ingress annotations
            annotations:
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
              kubernetes.io/ingress.class: alb
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
            # dashboard.ingress.tls -- Ingress TLS configuration
            tls: []
          # dashboard.priorityClassName -- Priority Class name to be used in deployment if provided.
          priorityClassName:

        webhook:
          # webhook.enable -- Whether to run the Validating Webhook
          enable: true
          # webhook.replicas -- Number of replicas
          replicas: 2
          # webhook.nodeSelector -- Webhook pod nodeSelector
          nodeSelector:
            kubernetes.io/os: linux
          # webhook.tolerations -- Webhook pod tolerations
          tolerations: []
          # webhook.affinity -- Webhook pods affinity
          affinity: {}
          # webhook.caBundle -- CA Bundle to use for Validating Webhook instead of cert-manager
          caBundle: {{ requiredEnv "POLARIS_CA_BUNDLE" }}
          # webhook.secretName -- Name of the secret containing a TLS certificate to use if cert-manager is not used.
          secretName: polaris-certificates
          # webhook.failurePolicy -- failurePolicy for the ValidatingWebhookConfiguration
          failurePolicy: Ignore
          # webhook.matchPolicy -- matchPolicy for the ValidatingWebhookConfiguration
          matchPolicy: Exact
          # webhook.namespaceSelector -- namespaceSelector for the ValidatingWebhookConfiguration
          namespaceSelector:
            matchExpressions:
            - key: control-plane
              operator: DoesNotExist
          # webhook.objectSelector -- objectSelector for the ValidatingWebhookConfiguration
          objectSelector: {}
          # webhook.rules -- An array of additional for the ValidatingWebhookConfiguration. Each requires a set of apiGroups, apiVersions, operations, resources, and a scope.
          rules: []
          # webhook.defaultRules -- An array of rules for common types for the ValidatingWebhookConfiguration
          defaultRules:
          - apiGroups:
            - apps
            apiVersions:
            - v1
            - v1beta1
            - v1beta2
            operations:
            - CREATE
            - UPDATE
            resources:
            - daemonsets
            - deployments
            - statefulsets
            scope: Namespaced
          - apiGroups:
            - batch
            apiVersions:
            - v1
            - v1beta1
            operations:
            - CREATE
            - UPDATE
            resources:
            - jobs
            - cronjobs
            scope: Namespaced
          - apiGroups:
            - ""
            apiVersions:
            - v1
            operations:
            - CREATE
            - UPDATE
            resources:
            - pods
            - replicationcontrollers
            scope: Namespaced
          # webhook.podAdditionalLabels -- Custom additional labels on webhook pods.
          podAdditionalLabels: {}
          # webhook.resources -- Requests and limits for the webhook.
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          # webhook.priorityClassName -- Priority Class name to be used in deployment if provided.
          priorityClassName:

        audit:
          # audit.enable -- Runs a one-time audit. This is used internally at Fairwinds, and may not be useful for others.
          enable: false
          # audit.cleanup -- Whether to delete the namespace once the audit is finished.
          cleanup: false
          # audit.outputURL -- A URL which will receive a POST request with audit results.
          outputURL: ""
```
* execute `helmfile -f polaris.yaml apply`
* create file `cronjob_without_tags_on_pod.yml` with content:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: terratest-cronjob-without-tags-on-pod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          # annotations:
          #   leaseplan/alert-channel: alert-test
          #   leaseplan/entity: lpdi
          #   leaseplan/environment: lpd-sandbox
          #   leaseplan/owner: andrea
          #   leaseplan/product: andrea-test
          #   leaseplan/service: eks-deploy-test
          #   leaseplan/version: no-version
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster test
            resources:
              requests:
                memory: 64m
                cpu: 10m
                ephemeral-storage: 10M
              limits:
                memory: 64m
                cpu: 10m
                ephemeral-storage: 10M
          nodeSelector:
            kubernetes.io/os: linux
          restartPolicy: Never
```
* run `kubectl apply -f cronjob_without_tags_on_pod.yml` (this should have failed)
* open polaris dashboard with portforwarding, see if the resource is visible or not

### Additional Context
No additional context

### References
No references
