### ISSUE TITLE
"Ingress does not have TLS configured" reported incorrectly for GKE

### ISSUE THREAD

**Issue by dulakm** [FairwindsOps/polaris#629]
### Installation Process
Installed by `kubectl` into the running cluster.

### Polaris Version
```
dashboard: quay.io/fairwinds/polaris:4.0
```

### Expected Behavior
"Ingress does not have TLS configured" not reported.

### Actual Behavior
"Ingress does not have TLS configured" being reported as an issue.

### Steps to Reproduce
Have the following Ingress in your GKE (Google Kubernetes Engine) cluster:
```
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: external-load-balancer
  annotations:
      kubernetes.io/ingress.global-static-ip-name: "external-ip"
      networking.gke.io/managed-certificates: "example.com"
      kubernetes.io/ingress.class: "gce"

spec:
  rules:
    - host: "example.com"
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: my-service
                port:
                  number: 80
```

### Additional Context
This configuration is according to [Google docs](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#setting_up_https_tls_between_client_and_load_balancer) the correct way on how to setup Ingress with TLS and managed SSL certificate. Therefore it shouldn't be marked as incorrect.

**Comment by rbren** [comment]
The example you sent in the Google docs is

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-2
spec:
  tls:
  - secretName: SECRET_NAME
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: SERVICE_NAME
            port:
              number: 60000
```

Note the `tls` field, which is not specified in your spec above. Am I missing something?
