### ISSUE TITLE
Multiple container image registries allowed

### ISSUE THREAD

**Issue by bygui86** [FairwindsOps/polaris#638]
How can I specify multiple allowed registries for container images?

I follow the example [here](https://polaris.docs.fairwinds.com/customization/custom-checks/#basic-example) but there is only quay registry specified:

```yaml
checks:
  imageRegistry: warning

customChecks:
  imageRegistry:
    successMessage: Image comes from allowed registries
    failureMessage: Image should not be from disallowed registry
    category: Security
    target: Container
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      properties:
        image:
          type: string
          not:
            pattern: ^quay.io
```

I tried different configurations:

```yaml
# attempt 1
customChecks:
...
          type: string
          not:
            pattern: ^quay.io|^docker.io|^eu.gcr.io

# attempt 2
customChecks:
...
          type: string
          anyOf:
            - ^quay.io
            - ^docker.io
            - ^eu.gcr.io

# attempt 3
customChecks:
...
          type: string
          required:
            - ^quay.io
            - ^docker.io
            - ^eu.gcr.io
```

but nothing seems to work :(

Thank you in advance for any help!

**Comment by rbren** [comment]
I think this should work (untested)
```yaml
checks:
  imageRegistry: warning

customChecks:
  imageRegistry:
    successMessage: Image comes from allowed registries
    failureMessage: Image should not be from disallowed registry
    category: Security
    target: Container
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      properties:
        image:
          type: string
          allOf:
          - not:
              pattern: ^quay.io
          - not:
              pattern: ^docker.io
```

**Comment by bygui86** [comment]
@rbren thanks for your suggestion, but unfortunately it does not work :(

at least 70% of my services come from `eu.grc.io` but I have following report using following config

```yaml
      properties:
        image:
          type: string
          allOf:
          - not:
              pattern: ^eu.grc.io
          - not:
              pattern: ^quay.io
          - not:
              pattern: ^docker.io
```

<img width="929" alt="Screenshot 2021-09-25 at 19 47 13" src="https://user-images.githubusercontent.com/22518997/134781166-0cfec185-92af-4c8a-a109-2248d5ec3694.png">

**Comment by rbren** [comment]
Sorry for the delay! I missed your update.

I misunderstood your question - I thought you were trying to create a _block_ list, rather than an _allow_ list. This schema should work:

```yaml
checks:
  imageRegistry: warning

customChecks:
  imageRegistry:
    successMessage: Image comes from allowed registries
    failureMessage: Image should not be from disallowed registry
    category: Security
    target: Container
    schema:
      '$schema': http://json-schema.org/draft-07/schema
      type: object
      properties:
        image:
          type: string
          oneOf:
          - pattern: ^eu.grc.io
          - pattern: ^docker.io
          - pattern: ^quay.io
```

**Comment by bygui86** [comment]
@rbren that's amazing! thanks a lot, it works!!

Now I have only one left doubt: what about images with nothing specified at the beginning? meaning from `docker.io`?

For example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  ...
  template:
    spec:
      ...
      containers:
        - name: traefik
          image: traefik
```
