### ISSUE TITLE
GitHub Actions - doc example results in error

### ISSUE THREAD

**Issue by HariSekhon** [FairwindsOps/polaris#681]
In a GitHub Actions workflow yaml I have this snippet taken directly from the doc page:

https://polaris.docs.fairwinds.com/infrastructure-as-code/#running-in-a-ci-pipeline

```
steps:
  - uses: actions/checkout@v2
  - name: Setup polaris
    uses: fairwindsops/polaris@master
    with:
      version: 4.0.7
```

Which results in the step getting the following error in GitHub Actions:

```
Warning: Unexpected input(s) 'version', valid inputs are ['entryPoint', 'args']
```

**Comment by HariSekhon** [comment]
I've worked around it like this:
```
    steps:
      - uses: actions/checkout@v2
      - name: Audit
        uses: fairwindsops/polaris@master
        with:
          #version: 4.0.7
          args: polaris audit --audit-path mydir -f pretty --only-show-failed-tests
```
