### ISSUE TITLE
[4.2.0] cli exemptions on Helm chart static analysis with annotations are not working

### ISSUE THREAD

**Issue by carlosjgp** [FairwindsOps/polaris#691]
### What happened?

polaris cli reports false positives (not successful checks) on helm charts after adding exceptions through annotations

### What did you expect to happen?

polaris cli keeps reporting errors on checks that have been addressed

### How can we reproduce this?

- Install polaris CLI 4.2.0
- Install Helm 3.5.3 (this is my version but a newer one should do too)
- Create a new chart `helm create test`
- Run polaris `polaris audit --only-show-failed-tests --helm-chart test --helm-values test/values.yaml --format yaml > init`
- Add `annotations.polaris.fairwinds.com/exempt=true` (or `polaris.fairwinds.com/privilegeEscalationAllowed-exempt=true`, neither works) to `deployment.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test.fullname" . }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
  annotations:
    polaris.fairwinds.com/exempt: true
...
```
- Run polaris `polaris audit --only-show-failed-tests --helm-chart test --helm-values test/values.yaml --format yaml > exempt`
- Check `diff init exempt`, a little bit difficult to see but the content is the same
```
$ wc exempt
 236  527 7971 exempt

$ wc init
 236  527 7971 init
```

I've also try the following command
```
helm template test -f test/values.yaml | polaris audit --only-show-failed-tests --audit-path=- --format yaml
```
with the same result

### version

4.2.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

looking for a way to ignore checks per chart basis

**Comment by daaain** [comment]
You might have figured it out, but just in case not: I needed to quote `true` for it to be picked up:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test.fullname" . }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
  annotations:
    polaris.fairwinds.com/exempt: "true"
```
