### ISSUE TITLE
Crash: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by megamorf** [FairwindsOps/polaris#760]
### What happened?

Polaris crashes when run with the `fix` subcommand:

```plaintext
▶ polaris fix --files-path base/manifests/deployment.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x213b7f5]

goroutine 1 [running]:
github.com/fairwindsops/polaris/cmd/polaris.getYamlFiles.func1({0xc000050180, 0x72}, {0x0, 0x0}, {0xc0000501f1, 0xc0002279e8})
	/go/src/github.com/fairwindsops/polaris/cmd/polaris/fix.go:137 +0x35
path/filepath.Walk({0xc000050180, 0x72}, 0xc0002279d0)
	/usr/local/go/src/path/filepath/path.go:503 +0x50
github.com/fairwindsops/polaris/cmd/polaris.getYamlFiles({0xc000050180, 0x7ff7bfeff5c9})
	/go/src/github.com/fairwindsops/polaris/cmd/polaris/fix.go:136 +0x4e
github.com/fairwindsops/polaris/cmd/polaris.glob..func3(0x34d3d20, {0x24dcd92, 0x2, 0x2})
	/go/src/github.com/fairwindsops/polaris/cmd/polaris/fix.go:56 +0xab
github.com/spf13/cobra.(*Command).execute(0x34d3d20, {0xc0000d8d60, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x34d3fa0)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/fairwindsops/polaris/cmd/polaris.Execute({0x24e51dc, 0xc0000001a0})
	/go/src/github.com/fairwindsops/polaris/cmd/polaris/root.go:88 +0x51
main.main()
	/go/src/github.com/fairwindsops/polaris/main.go:29 +0x25
```

### What did you expect to happen?

I expected polaris to update the yaml file with recommended settings.  

### How can we reproduce this?

Install via homebrew on MacOS (12.1 Monterey Intel)

```
▶ brew tap reactiveops/tap
▶ brew install reactiveops/tap/polaris
▶ brew info polaris
reactiveops/tap/polaris: stable 6.0.0
Open Source Best Practices for Kubernetes

/usr/local/Cellar/polaris/6.0.0 (5 files, 41.2MB) *
  Built from source on 2022-05-11 at 14:18:14
From: https://github.com/reactiveops/homebrew-tap/blob/HEAD/Formula/polaris.rb
```

Run `polaris fix` with the following yaml

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-awesome-service
  labels:
    app: my-awesome-service
spec:
  replicas: 3
  selector:
    matchLabels:
      name: my-awesome-service
  template:
    metadata:
      labels:
        name: my-awesome-service
    spec:
      restartPolicy: Always
      containers:
        - name: my-awesome-service
          image: my-awesome-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 2
              memory: 512Mi
          env:
            - name: MAS_API_MODE
              valueFrom:
                configMapKeyRef:
                  name: my-awesome-service-env-config
                  key: namespace_name
          volumeMounts:
            - name: app-config
              mountPath: /srv/config
      volumes:
        - name: app-config
          configMap:
            name: my-awesome-service-app-config
```

### Version

6.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
