### ISSUE TITLE
Namespaces without applied checks should be hidden

### ISSUE THREAD

**Issue by rassie** [FairwindsOps/polaris#853]
**Is your feature request related to a problem? Please describe.**
In a an OpenShift cluster, I've added an exemption on all `openshift-*` namespaces.

```
    exemptions:
    - controllerNames:
      - ""
      namespace: openshift
    - controllerNames:
      - ""
      namespace: openshift-apiserver
    - controllerNames:
      - ""
      namespace: openshift-apiserver-operator
    - controllerNames:
      - ""
      namespace: openshift-authentication
    - controllerNames:
      - ""
      namespace: openshift-authentication-operator
    - controllerNames:
      - ""
      namespace: openshift-cloud-controller-manager
    - controllerNames:
      - ""
      namespace: openshift-cloud-controller-manager-operator
[...]
```

However, these namespaces are still shown in the dashboard with "No checks applied" comment hidden in the collapsed section. 

![image](https://user-images.githubusercontent.com/23448/192480935-e11fbf42-f312-4beb-821f-ccecf53c6518.png)

This is unintuitive and noisy.

**Describe the solution you'd like**
Hide every namespace without applied checks in it.
