### ISSUE TITLE
Support custom categories & documentation URLs

### ISSUE THREAD

**Issue by bkrein-vertex** [FairwindsOps/polaris#854]
**Is your feature request related to a problem? Please describe.**

When writing custom checks it would be helpful to be able to put them into custom categories with custom documentation URLs  to set the `(?)` icon link to.

**Describe the solution you'd like**

Perhaps a new section in the config file to define custom categories like the following: 

```yaml
categories:
  - name: category1
    url: https://example.com/docs/category1
  - name: category2
    url: https://example.com/docs/category2
```

**Describe alternatives you've considered**

None.

**Additional context**

N/A
