### ISSUE TITLE
Ability to create a single exception for multiple namespaces 

### ISSUE THREAD

**Issue by bkrein-vertex** [FairwindsOps/polaris#881]
**Is your feature request related to a problem? Please describe.**
Currently it's possible to create a single exception that applies to multiple `controllerNames` across all namespaces but there's no way (that I see from the docs) to create a single exception that applies to a list of multiple namespaces.

**Describe the solution you'd like**
I'd like to be able to create an exemption like this: 

```yaml
exemptions:
  - namespaces:
      - namespace1
      - namespace2
      - namespace3
    rules:
      - rule1
      - rule2
```

**Describe alternatives you've considered**
Currently I have to either identify all the controllers within each namespace I want to exclude & list them individually or I have to create a separate exception for each namespace.  Neither scales particularly well.

```yaml
exemptions:
  - namespace:
      - namespace1
    rules:
      - rule1

  - namespace:
      - namespace2
    rules:
      - rule1

  - namespace:
      - namespace3
    rules:
      - rule1
```
