### ISSUE TITLE
Polaris Helm Chart: Add optional element additionalExemptions

### ISSUE THREAD

**Issue by ErikLundJensen** [FairwindsOps/polaris#900]
Polaris Helm Chart renders all configuration elements from a single field `config`. It is thereby not possible to add additional exemptions without replicating all the configurations into each and every usage of the helm chart.

For example, when deploying polaris to "cluster A" and to "cluster B" then we would like the same default exemptions for the two clusters, however, we would also like to add cluster specific exemptions.

**Solution**
Add optional element `additionalExemptions` to the Polaris Helm Chart
Thereby we can create a wrapper Helm Chart that contains the default configuration.
Example of usage:
```
apiVersion: v2
name: polaris-bar
description: A Helm chart for Fairwinds Polaris with specific defaults
version: 0.0.1
keywords: 
  - monitoring
  - security
dependencies:
  - name: polaris
    repository: https://charts.fairwinds.com/stable
    version: "5.6.0"
```
with default exemptions in the `values.yaml` file in that chart.

"Cluster A" can then use the Helm Chart `polaris-bar` and add extra exemptions:
```
additionalExemptions:
  - namespace: foo
    containerName:
      - hello
    rules:
      - privilegeEscalationAllowed
```
